# Display
WIDTH = 1280
HEIGHT = 720
# Assets
BACKGROUND = "assets/background.png"
PLAYER_IDLE = "assets/player/idle.png"
PLAYER_RIGHT = "assets/player/right.png"
PLAYER_LEFT = "assets/player/left.png"
METEOR_FRAMES = [
	"assets/meteor/FB001.png",
	"assets/meteor/FB002.png",
	"assets/meteor/FB003.png",
	"assets/meteor/FB004.png",
	"assets/meteor/FB005.png",
]

# Player
FRAME_WIDTH = 64
FRAME_HEIGHT = 128
FRAME_COUNT = 8
ANIMATION_SPEED = 150
PLAYER_W = 64
PLAYER_H = 128
STARTING_POS_W = WIDTH/2
STARTING_POS_H = HEIGHT - PLAYER_H
PLAYER_SPEED = 5
UPGRADE_COST = 100
SPEED_UPGRADE = 3

# Meteors
METEOR_WIDTH = 32
METEOR_HEIGHT = 64
METEOR_SCALE_MIN = 0.6
METEOR_SCALE_MAX = 1.6
METEOR_ANIMATION_SPEED = 100
OBS_SPEED_MIN = 4
OBS_SPEED_MAX = 9
CHAOS_SPEED_MULTIPLIER = 2
NEW_OBS_MIN = 400
NEW_OBS_MAX = 800
GAME_OVER_DELAY = 3000
RESPAWN_DELAY = 5000
CHAOS_SPAWN_INTERVAL = 100

# Timing
FPS = 60