#Window
WIDTH = 1280
HEIGHT = 720
#Assets
BACKGROUND = "assets/background.png"
PLAYER_IDLE = "assets/idle.png"
PLAYER_RIGHT = "assets/right.png"
PLAYER_LEFT = "assets/left.png"

#Player
FRAME_WIDTH = 64
FRAME_HEIGHT = 128
FRAME_COUNT = 8
ANIMATION_SPEED = 150
PLAYER_W = 64
PLAYER_H = 128
STARTING_POS_W = 500
STARTING_POS_H = HEIGHT - PLAYER_H
PLAYER_SPEED = 5

#Obstacles
OBS_W_MIN = 20 
OBS_W_MAX = 50
OBS_H_MIN = 15
OBS_H_MAX = 50
OBS_SPEED_MIN = 4
OBS_SPEED_MAX = 9
NEW_OBS_MIN = 400
NEW_OBS_MAX = 800

#Clock
FPS = 60